//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeriferia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class analista
    {
        internal int id;

        public int ID_ANALISTA { get; set; }
        public string NOMBRE_ANALISTA { get; set; }
        public int N_CASO { get; set; }
        public int TICKET { get; set; }
    }
}
