//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPeriferia.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class clienteperiferiaitEntities : DbContext
    {
        public clienteperiferiaitEntities()
            : base("name=clienteperiferiaitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analista> analista { get; set; }
        public virtual DbSet<cliente_externo> cliente_externo { get; set; }
        public virtual DbSet<soporte> soporte { get; set; }
    }
}
